apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqldatabases.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mysqlVersion:
                  type: string
                databaseName:
                  type: string
                user:
                  type: string
                password:
                  type: string
  scope: Namespaced
  names:
    plural: mysqldatabases
    singular: mysqldatabase
    kind: MySqlDatabase
    shortNames:
      - mdb

